### ISSUE TITLE
A question about the detection used in this paper

### ISSUE THREAD

**Issue by fandulu** [nhmduy/LMGP#5]
Thanks for your nice work! May I ask a question as to how to obtain detections in this paper? 

Ignoring the tracking performance, I find your detection of Table 1 is much better than previous works. However, as I know, current sota multi-view detection still cannot generate so good detections on WILDTRACK.

In your paper, it was mentioned
"We have demonstrated that nearly perfect multiple object tracking results can be obtained in crowded scenes given the right conditions (as for WILDTRACK)"
-> do you mean that GT detections are used for the tracking?

**Comment by nhmduy** [comment]
Hello, 

Yes, in our paper setting, we used GT detections provided in each dataset and fed it into the single-camera tracker (CenterTrack) to generate tracklets at each camera view. In summary, we only solve the tracking problem and use input public detections.

**Comment by fandulu** [comment]
Thanks so much for your quick replying.
