### ISSUE TITLE
About implementation details

### ISSUE THREAD

**Issue by chengche6230** [nhmduy/LMGP#6]
Hi, thanks for your great work!

I wonder what train-test split ratio used in each dataset.
In Wildtrack, many papers including yours follow the same standard, which is 90% for training and 10% for testing.
How about the other dataset like Campus and PETS09?

Thanks for your kind reply in advance.

**Comment by nhmduy** [comment]
Hello, 
For Campus: we used the beginning 10% of video data for training and the rest for testing. More details can be seen in [1], Section 5.1.
For PETS09, we used the 50% of frame for training and remain for testing followed [2].
I hope it helps you. Thank you.


[1] https://openaccess.thecvf.com/content_cvpr_2016/papers/Xu_Multi-View_People_Tracking_CVPR_2016_paper.pdf
[2] https://ps.is.mpg.de/uploads_file/attachment/attachment/357/iccv2013-siyu.pdf
